### PR TITLE
Some miscellaneous fixes

### LINKED ISSUE #336: [Recipe Issue]: Missing ME Infinity Dust Cell
### Modpack Version

1.1.2

### Describe the issue

All the materials that can be sieved exist a Infinity cell except for Dust.

### LINKED ISSUE #365: [Recipe Issue]: Compressed Netherack missing crushing recipe
### Modpack Version

1.21

### Describe the issue

Other recipes like compressed cobblestone allow for crushing inside the Crusher from Mekanism, while compressed netherrack only has the recipe to use the compressed hammers and not the Crusher from Mekanism.

Image

Image

### LINKED ISSUE #615: [Recipe Issue]:  Compressed Iron Ingot Seed missing
### Modpack Version

1.5

### Describe the issue

Image

in the picture shown there is a Compressed Iron Essence Recipe but no way to obtain the Seed for this. This should be removed or the Recipe added to get the essence. <3

### PR DESCRIPTION
**Pull request by doyle31**
3701e25b54163b62cdcc1cfb35099e72c72b93f7 fixes #336 
d951c50c509d96a93c88a6f8b6d0fe13a8a944d0 fixes #365 
e2ba3216cb5c733ca33204a11ba6b1d9464b9ffb fixes #615

### CODE REVIEW

File: kubejs/server_scripts/tweaks/allthecompressed.js [hunk 1]
```diff
@@ -61,6 +61,12 @@ ServerEvents.recipes((allthemods) => {
       crushing(ing, `allthecompressed:gravel_${i}x`)
     })
     crushing(`allthecompressed:gravel_${i}x`, `allthecompressed:sand_${i}x`)
+    crushing(`allthecompressed:sand_${i}x`, `allthecompressed:dust_${i}x`)
+
+    crushing(`allthecompressed:netherrack_${i}x`, `allthecompressed:crushed_netherrack_${i}x`)
+    crushing(`allthecompressed:blackstone_${i}x`, `allthecompressed:crushed_blackstone_${i}x`)
+    crushing(`allthecompressed:deepslate_${i}x`, `allthecompressed:crushed_deepslate_${i}x`)
```
Comment (oxalica) [inline kubejs/server_scripts/tweaks/allthecompressed.js]: Shouldn't this input be `cobbled_deepslate_${i}x` instead? This would be inconsistent with that, only cobblestone_*x is crush-able but not stone_*x.
